# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [9]:
output_data = "cities.csv"
city_data = pd.read_csv(output_data)

city_data_df = pd.DataFrame(city_data)
city_data_df.tail(5)

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
543,543,yabrud,0,SY,1558378840,32,33.97,36.66,80.60,8.05
544,544,paraiso,5,MX,1558378898,4,24.01,-104.61,84.20,16.11
545,545,veraval,0,FR,1558378898,62,49.65,0.71,61.00,8.05
546,546,novyy urgal,100,RU,1558378899,93,51.07,132.56,49.74,2.68
547,547,tongren,4,CN,1558378899,64,27.72,109.18,55.86,2.84

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
gmaps.configure(api_key=g_key)

locations = city_data_df[["Lat", "Lng"]].astype(float)

humidity = city_data_df["Humidity"]
fig = gmaps.figure()

heat = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=max(humidity),
                                 point_radius = 2)

fig.add_layer(heat)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [16]:
ideal_conditions_df = city_data_df

ideal_conditions_df= ideal_conditions_df.loc[(ideal_conditions_df["Max Temp"] < 80) & (ideal_conditions_df["Max Temp"] > 70)]
ideal_conditions_df = ideal_conditions_df.loc[ideal_conditions_df["Wind Speed"] < 15]
ideal_conditions_df = ideal_conditions_df.loc[ideal_conditions_df["Cloudiness"] == 0]

ideal_conditions_df = ideal_conditions_df.dropna()

ideal_conditions_df

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
56,56,pisco,0,PE,1558378764,30,-13.71,-76.20,75.99,11.41
70,70,ponta do sol,0,BR,1558378767,57,-20.63,-46.00,73.68,5.32
88,88,cidreira,0,BR,1558378770,66,-30.17,-50.22,76.56,5.50
114,114,koumac,0,NC,1558378775,68,-20.56,164.28,74.40,12.86
138,138,morondava,0,MG,1558378780,69,-20.30,44.28,79.08,9.06
139,139,vaini,0,IN,1558378780,88,15.34,74.49,78.90,1.59
176,176,nador,0,MA,1558378499,40,35.17,-2.93,75.20,6.93
297,297,mogok,0,MM,1558378844,51,22.92,96.51,72.24,2.77
444,444,birjand,0,IR,1558378880,26,32.86,59.22,71.60,9.17

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [17]:
hotel_df = ideal_conditions_df

hotel_df['Hotel Name'] = ''

# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}


for index, hotel in hotel_df.iterrows():
    Lat = hotel["Lat"]
    Lng = hotel["Lng"]

    # change location each iteration while leaving original params in place
    params["location"] = (f"{Lat},{Lng}")
    
    url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # assemble url and make API request
    response = requests.get(url, params=params).json()
    
    # extract results
    closest_hotel = response['results']
    
    try:
        print(f"Results for {index}: {hotel['City']}.")
        print(f"Closest hotel is {closest_hotel[0]['name']}.")
        hotel_df.loc[index, 'Hotel Name'] = closest_hotel[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        
    print("------------")

Results for 56: pisco.
Missing field/result... skipping.
------------
Results for 70: ponta do sol.
Missing field/result... skipping.
------------
Results for 88: cidreira.
Missing field/result... skipping.
------------
Results for 114: koumac.
Missing field/result... skipping.
------------
Results for 138: morondava.
Missing field/result... skipping.
------------
Results for 139: vaini.
Missing field/result... skipping.
------------
Results for 176: nador.
Missing field/result... skipping.
------------
Results for 297: mogok.
Missing field/result... skipping.
------------
Results for 444: birjand.
Missing field/result... skipping.
------------

In [12]:
hotel_df

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed,Hotel Name
56,56,pisco,0,PE,1558378764,30,-13.71,-76.20,75.99,11.41,
70,70,ponta do sol,0,BR,1558378767,57,-20.63,-46.00,73.68,5.32,
88,88,cidreira,0,BR,1558378770,66,-30.17,-50.22,76.56,5.50,
114,114,koumac,0,NC,1558378775,68,-20.56,164.28,74.40,12.86,
138,138,morondava,0,MG,1558378780,69,-20.30,44.28,79.08,9.06,
139,139,vaini,0,IN,1558378780,88,15.34,74.49,78.90,1.59,
176,176,nador,0,MA,1558378499,40,35.17,-2.93,75.20,6.93,
297,297,mogok,0,MM,1558378844,51,22.92,96.51,72.24,2.77,
444,444,birjand,0,IR,1558378880,26,32.86,59.22,71.60,9.17,

In [19]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [20]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations)
hotel_pins = gmaps.symbol_layer(
    locations, scale=2,
    info_box_content=hotel_info)

# Display figure
fig.add_layer(markers)
fig.add_layer(hotel_pins)
fig

Figure(layout=FigureLayout(height='420px'))